---
abstract: 'Modules to get info for/from PostScript fonts'
author:
  - 'Johan Vromans (jvromans@squirrel.nl)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PostScript-Font
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 2
  IO: 0
version: v1.10.03
