--- #YAML:1.0
name:                PostScript-Font
version:             1.10.02
abstract:            Modules to get info for/from PostScript fonts
license:             ~
author:              
    - Johan Vromans (jvromans@squirrel.nl)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Getopt::Long:                  2
    IO:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
